---
- hosts: all
  
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: safia2029
    group_name: devops
  vars_files:
    - variables.yml
    
  tasks:
    - name: Check the time
      command: ate
#     when: ansible_distribution == "safia" or ansible_processor_nproc == 2

    - name: Create user safia
      user:
         name: "{{ user_name }}"
         comment: Safia Admin

    - name: Create group
      group:
         name: "{{ group_name }}"
         state: present
      become: true
    - name: Install package
      package:
        name: "{{ pkg_name }}"
        state: present